### ISSUE TITLE
Transaction check crownjob intervall

### ISSUE THREAD

**Issue by Ocean15** [Doichain/dapp#10]
The transaction check intervall should be the same as the "new block" intervall

**Comment by inspiraluna** [comment]
how do you want to accomplish that? my suggestion: 
1. call getchaintips
2. getblock 
3. get time 
4. get previous block  (and get time of that one)  ... and so on ....
5. get the time of the previous 10 blocks and calculate the correct intervall.

**Comment by inspiraluna** [comment]
released in https://github.com/Doichain/dapp/releases/tag/v0.0.3
