### ISSUE TITLE
Add parameter to Send - dApp REST opt-in to use alternative template

### ISSUE THREAD

**Issue by inspiraluna** [Doichain/dapp#11]
In case a DOI request email is not critical in terms of time, a DOI request could be send out with a custom template. 

This template could be given through en URL as parameter in the opt-in REST-API request.

As @Ocean15 said this is almost implemented but not fully realized.

**Comment by SendFlo** [comment]
Doi request email templates can now be set via the POST or PUT API interface. Internationalizing is not handled, see issue #21
