### ISSUE TITLE
Use an other DOI validation email address

### ISSUE THREAD

**Issue by sines99** [Doichain/dapp#152]
At the moment the following e-mail address is used for the DOI e-mail: doichain@doichain.org

To avoid confusion, a self-speaking email address would be better.
Suggestion: validator@doichain.org, verify@doichain.org, or something similar.

**Comment by inspiraluna** [comment]
Good point! Thanks!

**Comment by inspiraluna** [comment]
<img width="311" alt="Bildschirmfoto 2020-12-15 um 18 49 53" src="https://user-images.githubusercontent.com/283618/102223302-d0b63600-3ee4-11eb-9cd0-ceb84e3e5716.png">
Testnet servers done! Please fix on production servers!

**Comment by inspiraluna** [comment]
<img width="629" alt="Bildschirmfoto 2021-01-07 um 14 03 55" src="https://user-images.githubusercontent.com/283618/103873152-a9abe800-50cf-11eb-8ab3-7e84c6275ab3.png">
done for mainnet validator!
