### ISSUE TITLE
When running tests from a fresh clone repo - dapp authentication seems wrong 

### ISSUE THREAD

**Issue by inspiraluna** [Doichain/dapp#155]
When starting a dAppp (or dapp-tests) 

meteor npm run regtest-alice on some computers test failes with "Unauthorized" -

The dApp tries to read the password from ~/.doichain/doichain.conf and stores this as dapp password.
if this file is not found it uses password as default password for the dApp - if it is found it stores that password for the dApp tests. This behaviour is fine for new installations. For developer machines sometimes a ~/.doichain/doichain.conf exists with another password (e.g. generated-password) in this case the dApp tests are failing. 

In case we run dApp-tests (regtest environment) it should not read ~/.doichain/doichain.conf

**Comment by leKg1** [comment]
TODO: error debugging - 3,5h
