### ISSUE TITLE
Display human readable info message when after confirming doi email a second time

### ISSUE THREAD

**Issue by inspiraluna** [Doichain/dapp#23]
when you click a second time on the confirmation link in the doi request email an unclear error message in JSON format appears in the browser. this should be improved by a better error message or better customizable template (e.g. like the email fallback template)

**Comment by SendFlo** [comment]
Repeated clicks on confirmation link in the confirmation email should lead to set redirect page. This needs to be fixed and tested.

**Comment by inspiraluna** [comment]
fixed, tested and released in 0.0.7.8
