### ISSUE TITLE
Claim blockhain entry without trial&error

### ISSUE THREAD

**Issue by Ocean15** [Doichain/dapp#5]
At the moment we try to make the name_firstupdate call repeatly until the transaction is mined but we should check for the new transactions and compare them with the name_new transaction. Thats more secure and wont throw the "txid not found" error all the time.

**Comment by inspiraluna** [comment]
maybe it will be possible to send a message to the dApp from namecoinD when a new transaction arrived! (like a calling a NewTransactionEvent()) I was thinking about this many times.

**Comment by inspiraluna** [comment]
name_new and name_firstupdate replaced by new name_doi command which saves data directly into the blockchain.

**Comment by inspiraluna** [comment]
released in https://github.com/Doichain/dapp/releases/tag/v0.0.3
