### ISSUE TITLE
Instant Doi Mails

### ISSUE THREAD

**Issue by Ocean15** [Doichain/dapp#6]
At the moment the doi mails will be send after 2 blocks at the earliest. Thats too slow in most common cases. We should let the send dapp communicate directly with the confirmation dapp so the doi mail will be send directly instead of waiting for the transactions to be confirmed. This will cause a security lack because one could use the doi mails as spam. Therefore we should forbid own doi mail templates from the send dapp and let the confirm dapp decide which doi template will be used for the mail.

**Comment by inspiraluna** [comment]
released in https://github.com/Doichain/dapp/releases/tag/v0.0.3
