### ISSUE TITLE
Make dapp available for multiple users via REST API

### ISSUE THREAD

**Issue by SendFlo** [Doichain/dapp#61]
1. It should be possible to create multiple accounts via REST
2. It should be possible to send a SOI-template-URL via REST
3. It should be possible to export user specific doi-information via REST

**Comment by SendFlo** [comment]
Users can be now created and updated by the admin in the [restAPIaccess](https://github.com/Doichain/dapp/tree/restAPIaccess) branch.

**Comment by SendFlo** [comment]
Doi-information are now exported by userid in export api query. In the future it should use user-id-token and auth-token.

**Comment by SendFlo** [comment]
- Authenticated users now can add opt-ins

- Template information is now optional on user creation and overwrites default template when fetched, if it exists

- Users can now export their opt-ins, admin can export all or just user specific

**Comment by SendFlo** [comment]
Need to add PUT call for users collection for users to be able to update their account-profile.
Admin user should still be able to update user-profiles based on userid.

**Comment by inspiraluna** [comment]
needs software tests.
