### ISSUE TITLE
Transfer registration fee to confirmation dapp

### ISSUE THREAD

**Issue by Ocean15** [Doichain/dapp#8]
At the moment the confirmation dapp will send doi mail "for free". We should let a doi request require a fee so its worth to install a confirmation dapp.

**Comment by inspiraluna** [comment]
Check if it is possible to transfer and additional the registration fee for "Confirm-dApp" inside a name_doi command.

**Comment by inspiraluna** [comment]
is implemented in https://github.com/Doichain/core/issues/10
