### ISSUE TITLE
DNS TXT entry namespacing

### ISSUE THREAD

**Issue by kosmonowt** [Doichain/dapp#85]
What if another provider which now for us is unknown also wants to use a DNS TXT key 

_opt-in-provider_ or _opt-in-key_ 

maybe it's better to use

_doi-opt-in-provider_ or _doi-opt-in-key_

for safer namespacing?

**Comment by inspiraluna** [comment]
@kosmonowt this was an error in the documentation! https://github.com/Doichain/dapp/blob/master/doc/de/install-manual-linux.md (it will be released with version 0.0.9)

see this example - we are using the "doichain prefix".

<img width="1006" alt="Bildschirmfoto 2019-05-06 um 13 18 44" src="https://user-images.githubusercontent.com/283618/57213888-96df3700-7001-11e9-9c26-c64b11e97443.png">
